 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: 
         name: "test"
         command: |
           echo $webdeploy
       - run: echo ${WEBDEPLOY}
       - run: echo $WEBDEPLOY
       - run: echo $webdeploy >> $publishprofile
       - run: echo $publishprofile
       - run: dotnet build StockMusicMasters.sln -nologo -p:PublishProfile=$publishprofile -p:DeployOnBuild=true -p:platform="Any CPU" -p:configuration="Release"
