 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run:
           name: "testing"
           command: |
             echo 'export MSDEPLOY_SERVICE_URL=$MSDeployServiceURL' >> $BASH_ENV
             echo 'export USERNAME=$UserName' >> $BASH_ENV
             echo 'export PASSWORD=$Password' >> $BASH_ENV
             echo 'export DESTINATION_CONNECTION_STRINGS=$DestinationConnectionStrings' >> $BASH_ENV
             echo 'export EFMIGRATIONS=$EFMigrations' >> $BASH_ENV
             source $BASH_ENV
             sed -i s@MSDEPLOY_SERVICE_URL@${MSDEPLOY_SERVICE_URL}@ 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml'
             sed -i s@USERNAME@${USERNAME}@ 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml'
             sed -i s@PASSWORD@${PASSWORD}@ 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml'
             sed -i s@DESTINATION_CONNECTION_STRINGS@${DESTINATION_CONNECTION_STRINGS}@ 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml'
             sed -i s@EFMIGRATIONS@${EFMIGRATIONS}@ 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml'
             echo "$(cat 'C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml')"
             dotnet build StockMusicMasters.sln -nologo -p:PublishProfile='C:\Users\circleci\project\StockMusicMasters\Properties\PublishProfiles\webdeploy.pubxml' -p:DeployOnBuild=true -p:platform="Any CPU" -p:configuration="Release"
           shell: bash.exe
